### ISSUE TITLE
Autocomplete for functions

### ISSUE THREAD

**Issue by LLZWWY** [stefankueng/BowPad#156] opened 2021-02-01 13:09 UTC
Hello! Can I add code completion function? I feel that this project is perfect and suitable for text editing. Compared with other ides, it is smaller and more convenient to use. However, other ides are used to code completion. Personally, if you can add this function, it will be more perfect. Because the project is smaller and more convenient. At present, I am using this project, but because of personal ability and familiarity with the development of this project.After thinking, although I don't think it's very OK, I still can't help asking the developer whether this function can be added.

**Comment by stefankueng** [comment] 2021-02-01 17:08
for autocompletion, we'd need a list of words to complete. Where would we get such a list?

**Comment by LLZWWY** [comment] 2021-02-02 01:20
The recording of words and notes is really a time-based project. However, you can make a board and fill in the words and instructions according to your own needs. In this way, the project will be much more economical, at the same time, users can adjust and compile different or diversified versions.

**Comment by wmjordan** [comment] 2021-02-02 08:12
I also suggest such a feature. I'd love to define my own lists to complete my XML files.

Some completion lists, for instance, a completion list for JavaScript programmers, can be shared between users like plugins today.

In EditPlus, the completion list can be customized by users, and EditPlus can automatically load a predefined list from all lists according to a given file type.

**Comment by stefankueng** [comment] 2021-02-05 18:25
there's still one problem: the autocomplete box in Scintilla is custom drawn, meaning there's no way to configure the colors. So in dark mode, that box would still be in light-mode.
I've tried the whole week to implement a custom box, but after hours of trying I found it's not possible without patching Scintilla.

**Comment by LLZWWY** [comment] 2021-02-06 05:34
> 还有一个问题:Scintilla中的自动完成框是自定义绘制的，这意味着无法配置颜色。所以在黑暗模式下，那个盒子仍然是在光明模式下。
> 我已经尝试了整整一周来实现一个定制的盒子，但是在几个小时的尝试之后，我发现如果不修补Scintilla是不可能的。

Notepad + + can be used for reference. This project is also designed with scintilla. Or direct self painting can produce changes according to different scenes, which is more humanized.

**Comment by LLZWWY** [comment] 2021-02-06 05:34
> there's still one problem: the autocomplete box in Scintilla is custom drawn, meaning there's no way to configure the colors. So in dark mode, that box would still be in light-mode.
> I've tried the whole week to implement a custom box, but after hours of trying I found it's not possible without patching Scintilla.

Notepad + + can be used for reference. This project is also designed with scintilla. Or direct self painting can produce changes according to different scenes, which is more humanized.

**Comment by stefankueng** [comment] 2021-02-06 08:08
notepad++ does not have a proper dark mode. And it does not have a custom autocomplete-popup either.

**Comment by LLZWWY** [comment] 2021-02-06 08:15
> notepad++ does not have a proper dark mode. And it does not have a custom autocomplete-popup either.

How about the feasibility of self drawing this scheme? Or write one according to the automatic completion scheme of monacoedit.

**Comment by stefankueng** [comment] 2021-02-06 09:07
As I said above: I've tried that this whole week.
but there's hope:
https://groups.google.com/g/scintilla-interest/c/Iov-C9-BUfM

**Comment by wmjordan** [comment] 2021-02-08 13:06
I don't care about the color of the auto-completion pop-up is not Black :)
Can I give it a try and see how it works?

**Comment by stefankueng** [comment] 2021-02-14 18:21
so guys, I need your help: to get a list of autocomplete words for languages (e.g. for C/C++, C#, ...)
The words can be set in an ini file located in %APPDATA%\BowPad\autocomplete.ini (or for portable versions in the bin folder). See an example file here:
https://github.com/stefankueng/BowPad/blob/main/src/res/AutoComplete.ini

so please, send me some word lists.

**Comment by wmjordan** [comment] 2021-02-15 00:13
Can we have an autocomplete which does things like Visual Studio?

For instance, in C/C++/C#, we have such definitions for autocomplete entries:
````ini
[AutoComplete]
lang=C,CPlusPlus,CSharp ; the following entries can be used in C, C++ and C#

if=if (^) {
}
for=for (int i^=0; i < length; i++) {
}

````
When a user types `if` and selects the corresponding entry in the popup, BowPad replaces it with the stuff at the right side of the equal sign and places the caret between `()` (where the first `^` is).

**Comment by stefankueng** [comment] 2021-02-15 06:05
@wmjordan what you're suggesting is not really autocompletion but a "code snippet" feature. I was planning to do that with a separate issue - the current code is already made so that the code snippet feature can be added easily later.

**Comment by wmjordan** [comment] 2021-02-15 10:36
Oh, I did not notice this.

Well, I'd gotten [a word list with the most commonly used 7001 English words](http://sherwoodschool.ru/en/vocabulary/) from a Russian site (single character words  "I" and "a" removed).

Can we use this in text files?
[common-7001.txt](https://github.com/stefankueng/BowPad/files/5980976/common-7001.txt)

**Comment by stefankueng** [comment] 2021-02-15 11:56
hmm - I don't think it's a good idea to have a word list for text files - not all users write text in English! But of course you can use that for yourself by putting such a list in your appdata dir.

**Comment by wmjordan** [comment] 2021-02-15 12:13
You are right. I seldom write in English either.
But I do not have any good idea about the completion lists in the current implementation yet.
I was supposed to try out the "code snippet" feature actually.

**Comment by wmjordan** [comment] 2021-02-16 00:04
I just notice the milestone is 2.6.6.
This is a very useful feature. I think it deserves a bigger version number.

**Comment by wmjordan** [comment] 2021-02-22 01:01
I have just compiled the latest commit and see the autocomplete function in action.

In a C++ file, `for`, `while` and `do` are working as expected.

If we type `if ` in a C++ file, since there is no corresponding snippet, an empty drop-down will be displayed. This may distract the user. If no snippet is available, no drop-down should be shown.

The XML auto-completion provides candidates for existing elements in the document, but the completion is no working.
There's a sample document.
````xml
<?xml version="1.0" standalone="yes"?>
<configuration>
  <appSettings>
    <add key="xx" value="xx" />
    <add key="yy" value="true" />
    <add key="dd" value="12" />
    <add key="m" value="adad" />
  </appSettings>
</configuration>
````

If we type `<a`, the completion gives two existing elements as the candidate: `add` and `appSettings`, however, when we select any of them and press Enter, nothing happens except that the popup disappears.

If we cancel the autocomplete, delete the string, (no more `<a` now) and type `<a` again, BowPad provides a new `a` entry in the list. Repeat the steps with `<ad` then the list becomes the following. It seems that those two entries should not appear in the list since they are not in the document.

![image](https://user-images.githubusercontent.com/12182730/108644766-5f4dc180-74eb-11eb-9853-e85f7a552908.png)

The popup no only appears when typing element names, but also when typing inside attribute values.

![image](https://user-images.githubusercontent.com/12182730/108645034-50b3da00-74ec-11eb-9ec2-630441d1bc64.png)

**Comment by stefankueng** [comment] 2021-02-22 18:42
autocompletion should work now as expected.
But I can't reproduce the issue where  "a" "ad", ... are added to the list.

And the autocompletion is shown everywhere in the editor/document. It would be very difficult to only show them in certain locations.

**Comment by wmjordan** [comment] 2021-02-23 00:30
To reproduce the issue where "a" "ad", ... are added to the list:

1. Use the above XML snippet  as a new document.
2. Enter a new line before `</configuration>` and type `<ad` there.
3. The completion list will show up.
4. Click outside of BowPad to make the window lose focus.
5. Click inside BowPad and use Backspace to delete `<ad`.
6. Type `<a` and you will see `ad` is added in to the list.

> autocompletion is shown everywhere in the editor/document

For XML documents, maybe things can be controlled if the autocompletion only serves tag names. Once the completion list is about to popup, you can check the content to the left of the caret and see whether it matches the `AutoCompleteRegex`. If it does not, don't popup the list.
But for other languages, things can be more complicated. Let's leave it along and see other users' feedback.

**Comment by stefankueng** [comment] 2021-02-23 20:57
ok, the regex was too eager, it matched scanned the doc while you were writing `<a` - and recognized the `a`. Fixed now.
As for the checking for the < in xml documents: while that would work, I'm planning to add xml keys as well to the autocompletion one day. Also, if we code something special for XML, then we'd have to do that for other languages as well.

But I think I'll make the autocomplete popup only popup after two or three chars are added, not for the first char.

**Comment by wmjordan** [comment] 2021-02-24 00:31
> if we code something special for XML, then we'd have to do that for other languages as well.

It may be too much for you.

Is it possible to disable the XML autocomplete regex and provide a dynamic set of snippets via scripting?
For instance, we may parse the XML schema and find out element names and their mandatory attributes and populate corresponding snippet. Or we parse the schema files when an XML document is loaded and then cache the snippet into a file. For documents loaded afterwards which reference the same schema files, the cached snippet will be loaded until the schema files are changed.
If a user changes the schema reference in the XML document, he can explicitly execute the script to update the snippets for the document.

**Comment by stefankueng** [comment] 2021-02-24 20:40
you could edit the userconfig file and add
```
[language]
Xml=xml;xmlx
[lang_Xml]
AutoCompleteRegex=
```
so that the regex is overwritten with an empty string.

But do you really only want auto-completion for xml tags? Not keys or even values?

**Comment by wmjordan** [comment] 2021-02-25 00:38
> But do you really only want auto-completion for xml tags? Not keys or even values?

Let's try the current implementation for a while and see.

I found a problem in the recent commits.
1. Use the above XML snippet as a new document.
2. Enter `<add`,
3. The completion list will show up.
4. Type `>` to complete the tag, now it is `<add></add>` in the editor and the caret is after the first "add".
5. The completion list is still there, and the selected item is "add".
6. Press Enter key, and the selected item will replace the content with "add".
7. Now it is `<add</add>` in the editor and the caret is after the first "add".

**Comment by wmjordan** [comment] 2021-02-26 00:34
I compiled the last commit.
It seems that there is no need to disable the auto-closing of XML tags.
Since `>` never appears in the completion list, when it is entered, we can just programmatically close the completion and auto-complete the tag.

**Comment by stefankueng** [comment] 2021-02-26 06:08
Yes, but the auto-closing of xml tags bothered me for a while now because it also closes when you correct something and hit > again, so you'll get two closing tags. Now if you type </ an autocomplete suggestion pops up - that's enough I think.

**Comment by wmjordan** [comment] 2021-02-26 07:28
> it also closes when you correct something and hit > again, so you'll get two closing tags

Usually we do something right, occasionally we do something wrong.
Thus we shall design for the mostly happened conditions.
How about that if we type `>`, BowPad firstly adds the `>` to the editor, then adds the closing tag afterward, instead of adding `></tagName>` at one batch. If the undesired _two closing tags_ do happen, we can Ctrl+Z to undo it immediately, just like what we can do if VS auto-completes something that we don't want.

**Comment by wmjordan** [comment] 2021-03-18 00:43
I saw the latest commit which has _stored the autocompletion word list in the lexer data_.

Shall we reuse the keyword list in the `Keywords1`, `Keywords2`, etc. properties for autocompletion?

**Closed** 2021-04-03 05:14 UTC
Labels: enhancement

**Comment by kitepad** [comment] 2022-06-19 05:24
Currently, auto completion is by lexer config. Can we have another auto completion style like scite (from scintilla.org)? It's triggered by key shortcut and list matched word in current document, config is not need.
