### ISSUE TITLE
Dark Theme Visibility Issue On "Other" Tab In Certain Sections

### ISSUE THREAD

**Issue by aluropod** [stefankueng/BowPad#363] opened 2023-12-24 17:36 UTC
First, I want to thank you for continuing to develop BowPad.  My operating system is Windows 10 22H2 64-bit and I use BowPad64-2.8.9-portable.zip.  There is an issue of visibility while in Dark Theme on the "Other" tab in some of its sections.  In the "Font" section, when you click the "Font Name" drop-down menu it is so dark it is hard to read.  Also in the "Font" section, the indicators "B" and "I", for Bold and Italic respectively, are such a dark blue they are hard to read.  In the "Plugins" section, when you click on the down arrow some entries in the list are such a dark gray they are hard to read.

Your efforts are greatly appreciated and I wish you all the best.

**Comment by stefankueng** [comment] 2024-01-15 18:04
duplicate of #345

**Closed by stefankueng** 2024-01-15 18:04 UTC
