### ISSUE TITLE
Horizontal scroll bar not visible on small file tree window due to bug.

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#120] opened 2020-12-09 04:18 UTC
To reproduce the problem:
1. Start bowpad. Close all documents. Turn off session auto load. Turn on filetree and make filetree very small, perhaps 10 pixels. Ensure bowpad remembers the tree size. Close bowpad.
2. Create an empty folder called c:\test1 and put an empty file in it called test1.txt.
3. Create an empty folder called c:\test2 and put an empty file in it called test2.txt.
4. Start bowpad then File Open c:\test1.txt, then c:\test2.txt
5. Note the filetree DOES NOT HAVE a horizontal scroll bar when test2.txt is active, but it SHOULD, like it does when test1.txt is active. This assumes you made file tree size very small as requested in step 1, to partially hide the path names for both folders.

To recreate problem easily:
With test2.txt active and test1.txt inactive, switch on session auto load and restart bowpad. The same problem is now easily repeatable just by starting bowpad.

**Comment by stefankueng** [comment] 2020-12-10 18:13
works fine for me.
What happens if the tree view is wider than 10px?

**Comment by gmcode** [comment] 2020-12-14 00:21
Hi
I made a mistake in my earlier summary, it's worse than I stated originally.

On re-testing, I find no horizontal scroll bar in the filetree, ever, no matter what size I resize the filetree to and no matter what files are loaded.

I can make vertical scroll bars appear in the filetree, but that's it, nothing I do makes horizontal bars appear.

I am using Windows 7, so you might have to try BP on that to see this problem.

**Comment by stefankueng** [comment] 2020-12-14 18:08
dupe of https://github.com/stefankueng/BowPad/issues/113

**Closed by stefankueng** 2020-12-14 18:08 UTC
Labels: duplicate

**Comment by gmcode** [comment] 2020-12-14 21:59
Experimenting has demonstrated that the problem is down to Bowpad's use of  WM_SETREDRAW.

The WM_SETREDRAW code in CFileTree::Refresh needs to be mindful of the WM_SETREDRAW code in WinMsgHandler's WM_THREADRESULTREADY handling and sync properly.

Putting the conditional line marked 'new' below into CFileTree::Refresh method appears to fix the problem for me:

    OnOutOfScope({
        if (!m_ThreadsRunning) // <-- New
            SendMessage(*this, WM_SETREDRAW, TRUE, 0);
    });

**Comment by gmcode** [comment] 2020-12-14 22:00
By the way, it would be good if these scroll bar's could be dark theme'd like bowpad's main window's scrollbars.

**Comment by stefankueng** [comment] 2020-12-15 19:19
the scrollbars are dark on Win10.

**Comment by stefankueng** [comment] 2020-12-15 19:21
yikes, your code would leave the redrawing disabled if threads are still running and not sending any results.

**Comment by stefankueng** [comment] 2020-12-15 19:23
also, both the WM_THREADRESULTSREADY and the Refresh() method are both executed on the main(UI) thread, so there's no 'sync' issue.

**Comment by gmcode** [comment] 2020-12-15 20:29
I said the code was "experimental" it was just to demonstrate there was an actual bug and it wasn't just some Windows 7 thing as you suggested and since you've committed a fix, that illustrates my point.

**Comment by gmcode** [comment] 2020-12-16 07:12
I've just tested your fix. It doesn't fix the scroll bar issue, if it is supposed to. What is your change trying to fix and what test case are you using to verify it fixes what you are trying to fix?

**Comment by gmcode** [comment] 2020-12-16 07:30
Another simple test case I am using is opening c:\bowpad\src\MainWindow.cpp and c:\test1\test1.txt, where test1.txt just has "hello" in it and then sizing the filetree to half cover the test1.txt filename, then closing and re-opening bowpad such that both files autoload. You should see at that time the filetree horizontal scrollbar is missing, which is the bug.

If you undo your patch and apply my experimental change, you should see the filetree horizontal is now present, regardless of whatever else you think is wrong with my patch.

So with this info, hopefully you can re-create the scenarios that show these facts and see what you have currently isn't solving this problem, but from there craft whatever fix you think is the right fix and then have a test case to see that it actually does indeed fix it.

**Comment by stefankueng** [comment] 2020-12-16 17:17
On my machine, the scrollbar is always shown, no matter what files I open on startup. Also when following the exact steps you mentioned, the scrollbar is shown for me.
Does the scrollbar appear if you resize the window?

**Comment by gmcode** [comment] 2020-12-16 21:34
The horizontal scrollbar appears if I resize the window, but it's not there on startup. So the steps are basically:
1. Close all documents and have autoload on.
2. Open c:\bowpad\src\MainWindow.cpp
3. Open c:\test\test1.txt that has just hello in it. My c:\test has only test1.txt (not that this matters).
4. With test1.txt being the current tab, resize the file tree so that it covers half the test1.txt filename.
5. Restart bowpad.

On restart, bowpad should automatically load both files with test1.txt being the active tab and the filetree window is still small sized as left previously, and still covering the test1.txt.  But on my machine the scroll bar is missing in this case, which is the bug. The scroll bar appears if the filetree is resized.

**Comment by stefankueng** [comment] 2020-12-17 18:50
repeating the same recipe as you did before won't help: as I said the scrollbar is always properly visible on the three computers I have access to.

But since this is only a glitch which is easily fixed by simply resizing, I won't spend any more time on this until I can reproduce this myself.
