### ISSUE TITLE
Opening files with blank paths does not work properly

### ISSUE THREAD

**Issue by xincanzhe** [stefankueng/BowPad#283] opened 2022-09-28 00:59 UTC
Use Bowpad 2.5.8 to replace the notepad of win11. However, opening files with blank paths after replacement does not work properly,The portable version of Bowpad is used.
then an error demonstration animation
![error](https://user-images.githubusercontent.com/70993225/192663465-f9cb3bd5-5da2-4c30-b0d2-60c6cba7c675.gif)

**Comment by stefankueng** [comment] 2022-09-28 16:39
you have to describe what you did to replace notepad with BP.
I'm guessing here but it seems you forgot to enclose the path parameter (usually it's `%1`) in quotes, e.g. `"%1"`

**Comment by xincanzhe** [comment] 2022-09-30 02:03
> you have to describe what you did to replace notepad with BP. I'm guessing here but it seems you forgot to enclose the path parameter (usually it's `%1`) in quotes, e.g. `"%1"`

I used the replacement method recommended by your official website. This method can open files without blank paths. It's no problem. I also tried to add the "% 1" parameter, but it didn't work.
I used the same method to replace it with notepad3, and this problem did not occur.
![image](https://user-images.githubusercontent.com/70993225/193172726-d36e26e7-057d-46d1-a030-145c4382c959.png)

**Comment by stefankueng** [comment] 2022-09-30 16:23
Close BowPad if you have it running.
Then open such a file so you get the error. Do not close BowPad but leave it running.
Open a Powershell console, then type:
`Get-CimInstance Win32_Process -Filter "name LIKE '%BowPad.exe%'" | Select CommandLine | format-list`
this will output the exact command line BowPad was started with. I would need that info.

**Comment by xincanzhe** [comment] 2022-10-03 01:00
> Close BowPad if you have it running. Then open such a file so you get the error. Do not close BowPad but leave it running. Open a Powershell console, then type: `Get-CimInstance Win32_Process -Filter "name LIKE '%BowPad.exe%'" | Select CommandLine | format-list` this will output the exact command line BowPad was started with. I would need that info.

This is the startup information captured by your method

![image](https://user-images.githubusercontent.com/70993225/193484885-56be44da-088b-43c8-9dab-76fae3f2d70c.png)

**Comment by stefankueng** [comment] 2022-10-05 16:59
thanks for the info.
But I can't reproduce this here, trying on two different machines. I never get the path to notepad after the /z.
Do you by any chance have an entry for bowpad.exe unter "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options" in the registry? If yes, then please remove that.

**Comment by stefankueng** [comment] 2022-10-06 20:21
very strange. I set up a VM and installed Win11 from scratch. I don't get the path to notepad.exe in the command line.
I'll try to implement a workaround...

**Comment by xincanzhe** [comment] 2022-10-07 01:46
> very strange. I set up a VM and installed Win11 from scratch. I don't get the path to notepad.exe in the command line. I'll try to implement a workaround...
I created the Notepad.exe subitem. In Windows 11 22XXX, you must uninstall the built-in UWP Notepad before you can use /z to replace Notepad. Win11 does not carry Notpad.exe subitem, need to create manually.

Open Files without Spaces can be used normally, eg: D:\cl.txt, but open Files with Spaces will have the bug, eg: D:\Program Files\CLion\build.txt

**Comment by wmjordan** [comment] 2022-10-26 08:43
This is not a bug of BowPad.
You should quote the /z as `"/z"` too.
````
"YOUR PATH TO BOWPAD\BowPad.exe" "/z"
````

**Comment by xincanzhe** [comment] 2022-10-26 14:07
> This is not a bug of BowPad. You should quote the /z as `"/z"` too.
> 
> ```
> "YOUR PATH TO BOWPAD\BowPad.exe" "/z"
> ```

It has been tested that this method does not work

**Comment by wmjordan** [comment] 2022-10-27 00:33
It works perfectly on my computer.
On your system, you have to substitute "YOUR PATH TO BOWPAD" to your path where BowPad is installed.

````
"D:\Program Files\BowPad\BowPad.exe" "/z"
````

**Comment by stefankueng** [comment] 2022-10-28 18:40
I've tried passing the exact command line you get with the powershell command to Bp - it opens the file correctly.
So there must be something else wrong. But since neither I nor @wmjordan can reproduce the problem, I'm closing this now as not reproducable.

**Closed by stefankueng** 2022-10-28 18:40 UTC
