### ISSUE TITLE
Modifying syntax highlighting not working

### ISSUE THREAD

**Issue by jrapdx-001** [stefankueng/BowPad#225] opened 2021-11-09 00:45 UTC
BowPad feature "Configure styles" isn't working with the Tcl lexer.

After installing BowPad (32 or 64bit) the configure style dialog accepts modifications. However on restarting BowPad all Tcl syntax highlighting is absent. Configure styles shows only "DEFAULT" for all text in the Tcl file.

If the BowPad directory in AppData\Roaming is deleted BowPad highlights Tcl with its standard scheme. Presence of "userconfig" with section "[SCLEX_TCL]" appears to be important because if the section is removed from "userconfig" the syntax highlighting reverts to the initial setup.

I haven't yet tried modifying styles of other lexers so have no info about how general the problem is.

(System is HP laptop with 11th gen Intel I7 running pre-release Windows 11.)

**Comment by jrapdx-001** [comment] 2021-11-09 08:06
These screenshots illustrate the problem described above:

![style-config-comment-ln-working](https://user-images.githubusercontent.com/93953827/140885572-36a37436-66c4-4159-b8e8-4ea4bb61db72.jpg)

![style-config-comment-ln-NOT-working](https://user-images.githubusercontent.com/93953827/140885616-1f7df016-4f77-4ba8-b5e0-460cd0f3f5d9.jpg)

The first image shows style config working as expected (on already opened files). The cursor is on a comment which is picked up by the dialog. 

Files opened in editor after style config is activated are not syntax highlighted at all. Even though the cursor is on a comment it's not picked up as a comment. _All_ Tcl syntax is "DEFAULT" in style config.

**Comment by stefankueng** [comment] 2021-11-09 17:14
please post the contents of your userconfig file once this happens.

**Comment by jrapdx-001** [comment] 2021-11-09 21:31
userconfig 
---------------

[hiddenLangs]
BowPadPlugin=hidden

[SCLEX_BASH]

[SCLEX_CPP]

[SCLEX_TCL]
Lexer=25
LexerName=
Style2=COMMENT LINE;008000;FFFFFF;;0;

-------------------------------------------

Note: Unless userconfig sections [SSCLEX_*] are empty (like [SCLEX_BASH]) there's no syntax highlighting at all when BowPad is closed and restarted. Happens with **all** languages including CSS, JS, etc.

**Comment by stefankueng** [comment] 2021-11-10 17:22
ups, I guess it's time for a new release: this is a dupe of #200 and has already been fixed.

**Closed by stefankueng** 2021-11-10 17:22 UTC

**Comment by stefankueng** [comment] 2021-11-10 17:30
btw: you can "fix" this by changing the line in userconfig:
```
[SCLEX_TCL]
Lexer=25
LexerName=
Style2=COMMENT LINE;008000;FFFFFF;;0;
```
to
```
[SCLEX_TCL]
Lexer=25
LexerName=tcl
Style2=COMMENT LINE;008000;FFFFFF;;0;
```

**Comment by jrapdx-001** [comment] 2021-11-11 06:32
Thank you for that hint, indeed it worked perfectly. Hopefully I won't encounter further issues with your excellent program.

Thanks again,
JRA

Nov 10, 2021 09:30:15 Stefan Küng ***@***.***>:
