### ISSUE TITLE
There is a slight flaw on the highlight selected word.

### ISSUE THREAD

**Issue by lizdDong** [stefankueng/BowPad#252] opened 2022-04-21 06:29 UTC
The last letter of the word will not be highlighted.

**Comment by stefankueng** [comment] 2022-04-21 11:11
fixed with [fc34b955644b510602ccc172aa9eee304ffde866](https://github.com/stefankueng/BowPad/commit/fc34b955644b510602ccc172aa9eee304ffde866)

Duplicate of #248

**Closed by stefankueng** 2022-04-21 11:11 UTC
Labels: duplicate
