### ISSUE TITLE
Some tabs got invisible on tab bar

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#351] opened 2023-10-03 03:25 UTC
I encountered that some tabs were missing on the tab bar. However, if I hovered the mouse cursor onto it, a tooltip would appear.

![shot](https://github.com/stefankueng/BowPad/assets/12182730/5f6acc66-2042-400e-815b-0cfde8ae0da0)

I had no idea how this happened.
It might be related to a bug about tab scrolling, when tabs overflowed in the bar.

**Comment by Wallby** [comment] 2023-11-21 19:06
For me too in version 2.8.9. Which tabs are shown depends on the size of the unmaximized window, upon maximizing the list of visible tabs doesn't update.

To demonstrate I opened 10 tabs here..
![image](https://github.com/stefankueng/BowPad/assets/13614975/ab0ede39-906a-4d73-8ca0-17a439268248)
![image](https://github.com/stefankueng/BowPad/assets/13614975/ef400930-c033-41b9-bdc1-a88b125e99f1)

**Comment by Wallby** [comment] 2024-01-30 21:07
Tried to track down the cause of this and noticed that `DrawItem` in TabBar.cpp is indeed not called for the selected tab (in my image "New 10") nor for any of the other tabs (in my image "New 8" and "New 9"). Thus I believe that is entirely the cause why they don't show up, but I am not sure what would be the right fix for it.

I created a patch with the changes I tried, which did seem to correctly track the visibility of the updown control called "spin" and also resulted in no tabs being hidden, but caused some artifacts. Not sure if any of what I tried is useful but sharing it anyway.

[0001-Tried-to-fix-invisible-tabs-issue-upon-maximizing-wi.patch](https://github.com/stefankueng/BowPad/files/14104126/0001-Tried-to-fix-invisible-tabs-issue-upon-maximizing-wi.patch)

**Comment by stefankueng** [comment] 2024-01-31 18:54
Thanks for the patch!
Change committed.

**Closed** 2024-01-31 18:54 UTC

**Comment by Wallby** [comment] 2024-02-01 11:24
> Tried to track down the cause of this and noticed that `DrawItem` in TabBar.cpp is indeed not called for the selected tab (in my image "New 10") nor for any of the other tabs (in my image "New 8" and "New 9"). Thus I believe that is entirely the cause why they don't show up, but I am not sure what would be the right fix for it.

I meant these two DrawItem calls by the way..
https://github.com/stefankueng/BowPad/blob/adc19be48ae0c105fa08b2ff513c22456fb55957/src/TabBar.cpp#L520
https://github.com/stefankueng/BowPad/blob/adc19be48ae0c105fa08b2ff513c22456fb55957/src/TabBar.cpp#L541

**Comment by Wallby** [comment] 2024-02-01 12:46
Created a pull request which should fix these artifacts.. https://github.com/stefankueng/BowPad/pull/367
