### ISSUE TITLE
wrap lines setting cannot take effect when open a new BowPad window

### ISSUE THREAD

**Issue by Yanstory** [stefankueng/BowPad#396] opened 2024-10-27 12:53 UTC
the `setting` file shows `View.wrapmode=1` but the namesake setting in new window always `off (false)`.

By click the button the setting value can be saved in file correctly. It just cannot work well when open a new BowPad window.

**Comment by stefankueng** [comment] 2024-11-01 10:18
dupe of #392

**Closed** 2024-11-13 18:44 UTC
Labels: duplicate

**Comment by Yanstory** [comment] 2024-11-14 03:16
The problem still exist.
![16AC17600C905D41B2D505DA868A6EBC](https://github.com/user-attachments/assets/48d6dfde-e808-4fdd-a1c7-62eeaccd113e)
