### ISSUE TITLE
Assign icon for plugin and add to Quick Access toolbar

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#112] opened 2020-11-26 07:22 UTC
Is it possible to assign an icon for an individual plugin and put the plugin to the Quick Access toolbar?

**Comment by stefankueng** [comment] 2020-11-26 17:53
unfortunately, it's not possible to add a plugin to the quick access toolbar. Only commands that are added via the [BowPad.xml](https://github.com/stefankueng/BowPad/blob/main/src/res/BowPad.xml) file can be added there, and that file is compiled as a resource. It's not possible to change that later. Sorry.

**Comment by wmjordan** [comment] 2020-11-27 00:15
Maybe there is still possibility for mission impossible.

Let's assume that users won't add more than 20 plugins to the bar.
We create an invisible place in the ribbon definition file, where 20 commands named from "UserCmd01" to "UserCmd20" are defined.
When a user try to place a plugin to the quick access bar, BowPad put one of those 20 commands onto that bar and associate that command with the plugin and its icon. And the next time another plugin is added, BowPad get another command which has not yet been associated and associate it with the plugin, until all 20 commands have been associated.

**Comment by stefankueng** [comment] 2020-11-28 08:02
while it's a good idea, it doesn't work :(
The problem here is that we need a dynamic container to show the plugins - a fixed one would show your 20 commands but only one or very few would be enabled (and no, there's no 'visible' flag that could be used). And dynamic containers don't allow to add their child-commands to the quick access bar.

**Comment by stefankueng** [comment] 2020-11-28 08:12
I think I found something that _might_ work. I'll keep you updated...

**Comment by stefankueng** [comment] 2020-11-28 14:39
unfortunately, my idea doesn't work.
The problem is that with all the gallery controls (i.e., the controls that have a dynamic list of child items/commands) only show the context menu to add the gallery control itself to the quick access toolbar, not the items/commands in their list. You can try that with any of those controls like lexer, Language, Tabs, ...

**Comment by wmjordan** [comment] 2020-11-29 02:47
Yes, the gallery controls are really a problem. I noticed that years ago once I began to work with BowPad.

Thank you for the explanation. I did not realize the limitation and just assumed that it was the same like the one in Office, which can be customized and programatically controlled.

How about using [Application modes](https://www.codeproject.com/Articles/228820/Ribbon-with-Cplusplus-Post-Ribbon-Dynamic-Struct)--Define those plugin place holder commands in application mode 1 (or some else values), which is invisible by default. Those commands can be added to the quick access bar despite of their invisibility.

Now the problem is how to add commands to the Quick Access bar programmatically.

**Comment by stefankueng** [comment] 2020-11-30 19:53
I tried to add plugin commands programmatically to the QAT - it doesn't work, and I don't know why not. I've added the commands to the xml file as well, with no luck.
Adding other commands programmatically works, just not for the plugins.

**Comment by wmjordan** [comment] 2020-12-01 01:29
If your adding other commands programmatically works, that's good.

Let's try the following not-so-clever approach:

1. Define 20 commands named `UserCmd0` thru `UserCmd19` which does nothing.
2. Assign all those commands with `ApplicationModes="1"` to hide them from default display--actually we are not going to show them on the Ribbon. They are just placeholders for plugins.

So, you've gotten 20 "other commands" that can be added to the QAT. But at this moment we have no way to add plugin commands to the QAT, since plugin commands are dynamically added to the gallery. If we can find some way to wire those installed plugins to the above 20 commands, it is possible to put them onto the QAT.

3. Create an string array sized 20. This array will be used to wire plugins to our 20 "other commands". Let's name it `PluginMap`.
4. Change the _Configure Plugins_ dialog, add a column named "Quick Access" to the "Installed Plugins" list. The content of that column may be a checkbox for each item. If checked, we fill the corresponding plugin name into the aforementioned `PluginMap`, if unchecked, we remove it from the array.
5. When we click the Ok button in the dialog, BowPad scans the `PluginMap`. Once it finds a not-`null` entry, it places command `"UserCmd"+indexInPluginMap.toString()` to the QAT.
6. Change the command handler for those `UserCmd*` commands. When a user clicks `UserCmd*` in the QAT, BowPad looks up the `PluginMap` array with the number at the end of the command name. If the entry is a plugin name, BowPad executes corresponding plugin.

BowPad should also persists the `PluginMap` so it can restore the plugin commands in QAT in the next time.

We just assume that a user will not put more than 20 commands on to the QAT.

**Comment by stefankueng** [comment] 2020-12-01 18:12
that's pretty much what I'm planning to try tonight 🥇 :)

**Comment by stefankueng** [comment] 2020-12-01 20:41
I'm making some headway here.
but on a side note: with the plugin commands now implemented as real commands, the IsEnabled() function of a plugin is now considered. Which means a plugin that needs its IsEnabled() state to update according to e.g. a selection change also needs to invalidate its state (without that, the ribbon does not ask for the enabled state!):

```
// notification from the Scintilla control
function ScintillaNotify(code, position, ch, modifiers, modificationType, text, length, linesAdded, message, wParam, lParam, line, foldLevelNow, foldLevelPrev, margin, listType, x, y, token, annotationLinesAdded, updated) {
	if (code == 2007 && (updated & 0x02)) {	//SCN_UPDATEUI
		BowPad.InvalidateState();
	}
}

```

**Comment by wmjordan** [comment] 2020-12-02 00:12
OMG, there are so many parameters in the above function!

**Comment by stefankueng** [comment] 2020-12-02 18:47
those are all the parameters that the scintilla notification provides.

**Closed** 2020-12-02 18:47 UTC
Labels: enhancement

**Comment by wmjordan** [comment] 2020-12-03 01:14
Thank you for the hard work!

It seems that we have not yet provided a way to add plugins to the QAT.

**Comment by stefankueng** [comment] 2020-12-03 16:52
yes you can: hit Ctrl+Shift+P to bring up the command palette, find your plugin there, right-click and then add it to the QAT.

**Comment by wmjordan** [comment] 2020-12-04 00:13
Oh, I see.
It is a bit hard to find this way. Few users will realize that, i am afraid.

**Comment by wmjordan** [comment] 2020-12-08 09:50
After the update, I found that the SearchSelection plugin was always gray.
How can I activate it?

**Comment by stefankueng** [comment] 2020-12-08 19:10
you need to call BowPad.InvalidateState() whenever the selection changes.
Use the code from https://github.com/stefankueng/BowPad/issues/112#issuecomment-736806960

**Comment by wmjordan** [comment] 2020-12-09 00:23
Oh, I see. Thank you!

**Comment by wmjordan** [comment] 2020-12-09 09:58
Plugin icons are very huge on Windows 7 (see below). On other OSes they are normal.

![image](https://user-images.githubusercontent.com/12182730/101614481-f73d2280-3a47-11eb-84d0-5ce79b05ba72.png)
